save_predictions_and_refs: True
dt: 0.01
rate: 100
horizon_size: 20
armature: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
gripper_weight: 500
state_weight: 5
control_weight: 0.001
max_qp_iter: 100
max_iter: 7
use_vision: False
use_vision_simulated: True
start_visual_servoing_dist: 0.03
effector_frame_name: "panda_hand_tcp"
use_constraints: True
increasing_weights:
    max: 200
    percent: 0.9
    time_reach_percent: 4
activate_callback: False

